### ISSUE TITLE
Facing issue while running docker image on my mac

### ISSUE THREAD

**Issue by tsprasath** [viyh/whisper#2]
✔ docker run --name whisper \
        -p 8000:8000 \
        -e SECRET_KEY=thi\$1smyC00L5ecr3t \
        -it viyh/whisper:dependabot_pip_app_flask-cors-3.0.9
==> /tmp/gunicorn.error.log <==

==> /tmp/nginx.error.log <==

==> /tmp/nginx.access.log <==

==> /tmp/gunicorn.error.log <==
[2022-02-23 14:47:05 +0000] [11] [INFO] Starting gunicorn 19.9.0
[2022-02-23 14:47:05 +0000] [11] [INFO] Listening at: unix:/tmp/gunicorn.sock (11)
[2022-02-23 14:47:05 +0000] [11] [INFO] Using worker: sync
[2022-02-23 14:47:05 +0000] [16] [INFO] Booting worker with pid: 16
[2022-02-23 14:47:07 +0000] [16] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/usr/src/app/app.py", line 198, in <module>
    dynamodb = boto3.resource('dynamodb')
  File "/usr/local/lib/python3.7/site-packages/boto3/__init__.py", line 100, in resource
    return _get_default_session().resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/boto3/session.py", line 389, in resource
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 838, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 86, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 328, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 47, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 117, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 402, in resolve
    service_name, region_name)
  File "/usr/local/lib/python3.7/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/usr/local/lib/python3.7/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
[2022-02-23 14:47:07 +0000] [16] [INFO] Worker exiting (pid: 16)
[2022-02-23 14:47:07 +0000] [11] [INFO] Shutting down: Master
[2022-02-23 14:47:07 +0000] [11] [INFO] Reason: Worker failed to boot.

==> /tmp/nginx.error.log <==
2022/02/23 14:47:24 [crit] 14#14: *2 connect() to unix:/tmp/gunicorn.sock failed (2: No such file or directory) while connecting to upstream, client: 172.17.0.1, server: whisper, request: "GET / HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock:/", host: "localhost:8000"
2022/02/23 14:47:24 [error] 14#14: *2 open() "/usr/src/app/static/500.html" failed (2: No such file or directory), client: 172.17.0.1, server: whisper, request: "GET / HTTP/1.1", upstream: "http://unix:/tmp/gunicorn.sock/", host: "localhost:8000"

==> /tmp/nginx.access.log <==
172.17.0.1 - - [23/Feb/2022:14:47:24 +0000] "GET / HTTP/1.1" 404 555 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/20708426/155342918-027f569d-4a20-44f6-a301-be6b06812b3a.png">

**Comment by viyh** [comment]
It looks like you aren't mounting AWS credentials, so you'll need to specify them in the env vars in your Docker run command by adding something like this:

    docker run --name whisper -p 8000:8000 \
        -e AWS_ACCESS_KEY_ID=YOUR_AWS_ACCESS_KEY_ID \
        -e AWS_SECRET_ACCESS_KEY=YOUR_AWS_SECRET_ACCESS_KEY \
        -e AWS_DEFAULT_REGION=us-east-1 \
        -e SECRET_KEY=thi\$1smyC00L5ecr3t \
        -it viyh/whisper

The README has a section about how to use the AWS creds. That said, I've been working on a rewrite that is almost complete and should be much improved. I will be completing it hopefully over the next week or so.
